version = 1

test_patterns = [
  "tests/**/*",
  "test/**/*",
  "__tests__/**/*",
  "**/*.test.js",
  "**/*.test.ts",
  "**/*.test.tsx",
]

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.configs]
  tsconfig = "./tsconfig.json" # If using TypeScript

  eslint_config = "./.eslintrc.json" # Path to your ESLint configuration file

  jsx = true

