version = 1

# The test_patterns are the files or directories that should be excluded from analysis.
test_patterns = [
  "tests/**/*",
  "test/**/*",
  "__tests__/**/*",
  "**/*.test.js",
  "**/*.test.ts",
  "**/*.test.tsx",
]

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  runtime_version = "16.x.x" # Set the Node.js version used in your project

  [analyzers.configs]
  # This enables TypeScript support if your React project uses TypeScript
  tsconfig = "./tsconfig.json"

  # ESLint configuration
  eslint_config = "./.eslintrc.json" # Path to your ESLint configuration file

  # Enable JSX support
  jsx = true
